In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/transactions_data.csv")

print(f"Satır sayısı : {len(df):,}")
print(f"Kolon sayısı : {len(df.columns)}")
print(f"Kolonlar     : {list(df.columns)}")
df.head()

ModuleNotFoundError: No module named 'pandas'

In [2]:
import subprocess
subprocess.run(["pip", "install", "pandas", "numpy"])

CompletedProcess(args=['pip', 'install', 'pandas', 'numpy'], returncode=1)

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/transactions_data.csv")

print(f"Satır sayısı : {len(df):,}")
print(f"Kolon sayısı : {len(df.columns)}")
print(f"Kolonlar     : {list(df.columns)}")
df.head()

ModuleNotFoundError: No module named 'pandas'

In [4]:
import sys
subprocess.run([sys.executable, "-m", "pip", "install", "pandas", "numpy"])

CompletedProcess(args=['c:\\financeai\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'pandas', 'numpy'], returncode=0)

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/transactions_data.csv")

print(f"Satır sayısı : {len(df):,}")
print(f"Kolon sayısı : {len(df.columns)}")
print(f"Kolonlar     : {list(df.columns)}")
df.head()

Satır sayısı : 13,305,915
Kolon sayısı : 12
Kolonlar     : ['id', 'date', 'client_id', 'card_id', 'amount', 'use_chip', 'merchant_id', 'merchant_city', 'merchant_state', 'zip', 'mcc', 'errors']

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors
0,7475327,2010-01-01 00:01:00,1556,2972,$-77.00,Swipe Transaction,59935,Beulah,ND,58523.0,5499,NaN
1,7475328,2010-01-01 00:02:00,561,4575,$14.57,Swipe Transaction,67570,Bettendorf,IA,52722.0,5311,NaN
2,7475329,2010-01-01 00:02:00,1129,102,$80.00,Swipe Transaction,27092,Vista,CA,92084.0,4829,NaN
3,7475331,2010-01-01 00:05:00,430,2860,$200.00,Swipe Transaction,27092,Crown Point,IN,46307.0,4829,NaN
4,7475332,2010-01-01 00:06:00,848,3915,$46.41,Swipe Transaction,13051,Harwood,MD,20776.0,5813,NaN

In [6]:
print(df.dtypes)
print(df.isnull().sum())
df.describe()

id                  int64
date                  str
client_id           int64
card_id             int64
amount                str
use_chip              str
merchant_id         int64
merchant_city         str
merchant_state        str
zip               float64
mcc                 int64
errors                str
dtype: object
id                       0
date                     0
client_id                0
card_id                  0
amount                   0
use_chip                 0
merchant_id              0
merchant_city            0
merchant_state     1563700
zip                1652706
mcc                      0
errors            13094522
dtype: int64

,id,client_id,card_id,merchant_id,zip,mcc
count,1.330592e+07,1.330592e+07,1.330592e+07,1.330592e+07,1.165321e+07,1.330592e+07
mean,1.558402e+07,1.026812e+03,3.475268e+03,4.772376e+04,5.132782e+04,5.565440e+03
std,4.704499e+06,5.816386e+02,1.674356e+03,2.581534e+04,2.940423e+04,8.757002e+02
min,7.475327e+06,0.000000e+00,0.000000e+00,1.000000e+00,1.001000e+03,1.711000e+03
25%,1.150604e+07,5.190000e+02,2.413000e+03,2.588700e+04,2.860200e+04,5.300000e+03
50%,1.557087e+07,1.070000e+03,3.584000e+03,4.592600e+04,4.767000e+04,5.499000e+03
75%,1.965361e+07,1.531000e+03,4.901000e+03,6.757000e+04,7.790100e+04,5.812000e+03
max,2.376187e+07,1.998000e+03,6.144000e+03,1.003420e+05,9.992800e+04,9.402000e+03

In [7]:
df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)
df['date'] = pd.to_datetime(df['date'])
df['errors'] = df['errors'].fillna('No Error')
df['merchant_state'] = df['merchant_state'].fillna('Unknown')
df['zip'] = df['zip'].fillna(0).astype(int).astype(str)
df['zip'] = df['zip'].replace('0', 'Unknown')
df = df.drop_duplicates()
print(f"Temiz satır sayısı: {len(df):,}")

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Ebra Nur Sayar\AppData\Local\Temp\ipykernel_15172\1797440570.py:1: SyntaxWarning: invalid escape sequence '\$'
  df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)

Temiz satır sayısı: 13,305,915

In [8]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['hour'] = df['date'].dt.hour
df['is_weekend'] = df['date'].dt.dayofweek.isin([5,6]).astype(int)
df['transaction_type'] = df['amount'].apply(lambda x: 'Gelir' if x > 0 else 'Gider')
df['abs_amount'] = df['amount'].abs()
df.head()

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,year,month,hour,is_weekend,transaction_type,abs_amount
0,7475327,2010-01-01 00:01:00,1556,2972,-77.00,Swipe Transaction,59935,Beulah,ND,58523,5499,No Error,2010,1,0,0,Gider,77.00
1,7475328,2010-01-01 00:02:00,561,4575,14.57,Swipe Transaction,67570,Bettendorf,IA,52722,5311,No Error,2010,1,0,0,Gelir,14.57
2,7475329,2010-01-01 00:02:00,1129,102,80.00,Swipe Transaction,27092,Vista,CA,92084,4829,No Error,2010,1,0,0,Gelir,80.00
3,7475331,2010-01-01 00:05:00,430,2860,200.00,Swipe Transaction,27092,Crown Point,IN,46307,4829,No Error,2010,1,0,0,Gelir,200.00
4,7475332,2010-01-01 00:06:00,848,3915,46.41,Swipe Transaction,13051,Harwood,MD,20776,5813,No Error,2010,1,0,0,Gelir,46.41

In [9]:
import json
with open('../data/mcc_codes.json', 'r') as f:
    mcc_dict = json.load(f)

df['mcc_str'] = df['mcc'].astype(str)
df['kategori'] = df['mcc_str'].map(mcc_dict).fillna('Diğer')
print(df['kategori'].value_counts().head(15))

kategori
Grocery Stores, Supermarkets                  1592584
Miscellaneous Food Stores                     1460875
Service Stations                              1424711
Eating Places and Restaurants                  999738
Drug Stores and Pharmacies                     772913
Tolls and Bridge Fees                          674135
Wholesale Clubs                                601942
Money Transfer                                 589140
Taxicabs and Limousines                        500662
Fast Food Restaurants                          499659
Automotive Service Shops                       478263
Department Stores                              475384
Drinking Places (Alcoholic Beverages)          248570
Discount Stores                                246545
Utilities - Electric, Gas, Water, Sanitary     242993
Name: count, dtype: int64

In [10]:
df.to_parquet('../data/transactions_clean.parquet', index=False)
print("✅ Kaydedildi!")

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.

In [11]:
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "pyarrow", "--break-system-packages"])

CompletedProcess(args=['c:\\financeai\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'pyarrow', '--break-system-packages'], returncode=0)

In [1]:
df.to_csv('../data/transactions_clean.csv', index=False)
print("✅ Kaydedildi!")

NameError: name 'df' is not defined

In [2]:
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "pandas", "numpy", "pyarrow"])

import pandas as pd
import numpy as np
import json

# Veri yükle
df = pd.read_csv("../data/transactions_data.csv")
print(f"Yüklendi: {len(df):,} satır")

# Temizle
df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)
df['date'] = pd.to_datetime(df['date'])
df['errors'] = df['errors'].fillna('No Error')
df['merchant_state'] = df['merchant_state'].fillna('Unknown')
df['zip'] = df['zip'].fillna(0).astype(int).astype(str)
df['zip'] = df['zip'].replace('0', 'Unknown')
df = df.drop_duplicates()
print(f"Temizlendi: {len(df):,} satır")

# Yeni kolonlar
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['hour'] = df['date'].dt.hour
df['is_weekend'] = df['date'].dt.dayofweek.isin([5,6]).astype(int)
df['transaction_type'] = df['amount'].apply(lambda x: 'Gelir' if x > 0 else 'Gider')
df['abs_amount'] = df['amount'].abs()

# MCC kategorileri
with open('../data/mcc_codes.json', 'r') as f:
    mcc_dict = json.load(f)

df['mcc_str'] = df['mcc'].astype(str)
df['kategori'] = df['mcc_str'].map(mcc_dict).fillna('Diğer')
print(f"Kategoriler eklendi")

# Kaydet
try:
    df.to_parquet('../data/transactions_clean.parquet', index=False)
    print("✅ Parquet olarak kaydedildi!")
except:
    df.to_csv('../data/transactions_clean.csv', index=False)
    print("✅ CSV olarak kaydedildi!")

df.head()

<>:13: SyntaxWarning: invalid escape sequence '\$'
<>:13: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Ebra Nur Sayar\AppData\Local\Temp\ipykernel_3876\3842564577.py:13: SyntaxWarning: invalid escape sequence '\$'
  df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)

Yüklendi: 13,305,915 satır
Temizlendi: 13,305,915 satır
Kategoriler eklendi

C:\Users\Ebra Nur Sayar\AppData\Local\Temp\ipykernel_3876\3842564577.py:13: SyntaxWarning: invalid escape sequence '\$'
  df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)

OSError: [Errno 28] No space left on device

In [3]:
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "pandas", "numpy", "pyarrow"])

import pandas as pd
import numpy as np
import json

# Veri yükle
df = pd.read_csv("../data/transactions_data.csv")
print(f"Yüklendi: {len(df):,} satır")

# Temizle
df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)
df['date'] = pd.to_datetime(df['date'])
df['errors'] = df['errors'].fillna('No Error')
df['merchant_state'] = df['merchant_state'].fillna('Unknown')
df['zip'] = df['zip'].fillna(0).astype(int).astype(str)
df['zip'] = df['zip'].replace('0', 'Unknown')
df = df.drop_duplicates()
print(f"Temizlendi: {len(df):,} satır")

# Yeni kolonlar
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['hour'] = df['date'].dt.hour
df['is_weekend'] = df['date'].dt.dayofweek.isin([5,6]).astype(int)
df['transaction_type'] = df['amount'].apply(lambda x: 'Gelir' if x > 0 else 'Gider')
df['abs_amount'] = df['amount'].abs()

# MCC kategorileri
with open('../data/mcc_codes.json', 'r') as f:
    mcc_dict = json.load(f)

df['mcc_str'] = df['mcc'].astype(str)
df['kategori'] = df['mcc_str'].map(mcc_dict).fillna('Diğer')
print(f"Kategoriler eklendi")

# Kaydet
try:
    df.to_parquet('../data/transactions_clean.parquet', index=False)
    print("✅ Parquet olarak kaydedildi!")
except:
    df.to_csv('../data/transactions_clean.csv', index=False)
    print("✅ CSV olarak kaydedildi!")

df.head()

<>:13: SyntaxWarning: invalid escape sequence '\$'
<>:13: SyntaxWarning: invalid escape sequence '\$'
C:\Users\Ebra Nur Sayar\AppData\Local\Temp\ipykernel_3876\2318163944.py:13: SyntaxWarning: invalid escape sequence '\$'
  df['amount'] = df['amount'].replace('[\$,]', '', regex=True).astype(float)

Yüklendi: 13,305,915 satır
Temizlendi: 13,305,915 satır
Kategoriler eklendi
✅ Parquet olarak kaydedildi!

,id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip,mcc,errors,year,month,hour,is_weekend,transaction_type,abs_amount,mcc_str,kategori
0,7475327,2010-01-01 00:01:00,1556,2972,-77.00,Swipe Transaction,59935,Beulah,ND,58523,5499,No Error,2010,1,0,0,Gider,77.00,5499,Miscellaneous Food Stores
1,7475328,2010-01-01 00:02:00,561,4575,14.57,Swipe Transaction,67570,Bettendorf,IA,52722,5311,No Error,2010,1,0,0,Gelir,14.57,5311,Department Stores
2,7475329,2010-01-01 00:02:00,1129,102,80.00,Swipe Transaction,27092,Vista,CA,92084,4829,No Error,2010,1,0,0,Gelir,80.00,4829,Money Transfer
3,7475331,2010-01-01 00:05:00,430,2860,200.00,Swipe Transaction,27092,Crown Point,IN,46307,4829,No Error,2010,1,0,0,Gelir,200.00,4829,Money Transfer
4,7475332,2010-01-01 00:06:00,848,3915,46.41,Swipe Transaction,13051,Harwood,MD,20776,5813,No Error,2010,1,0,0,Gelir,46.41,5813,Drinking Places (Alcoholic Beverages)